// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMETwz8UNrfsGmxK3h5eioZsQwcP4ORAU',
    appId: '1:49430381094:web:7ee1a862c14e828d839ce7',
    messagingSenderId: '49430381094',
    projectId: 'mynotes-a1859',
    authDomain: 'mynotes-a1859.firebaseapp.com',
    storageBucket: 'mynotes-a1859.appspot.com',
    measurementId: 'G-E8DHLW3VDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBec_c5F2YGzKU4AMaK2FqXDOkr54LEWp4',
    appId: '1:49430381094:android:bd0edb74de469557839ce7',
    messagingSenderId: '49430381094',
    projectId: 'mynotes-a1859',
    storageBucket: 'mynotes-a1859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0zAZ0SObPVCnBTFAwzI9O-6wF1DzDOng',
    appId: '1:49430381094:ios:6f353fbc43696163839ce7',
    messagingSenderId: '49430381094',
    projectId: 'mynotes-a1859',
    storageBucket: 'mynotes-a1859.appspot.com',
    iosBundleId: 'com.imadlol.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0zAZ0SObPVCnBTFAwzI9O-6wF1DzDOng',
    appId: '1:49430381094:ios:6eea55da638a8795839ce7',
    messagingSenderId: '49430381094',
    projectId: 'mynotes-a1859',
    storageBucket: 'mynotes-a1859.appspot.com',
    iosBundleId: 'com.imadlol.mynotes.RunnerTests',
  );
}
